SELECT * FROM CUSTOMER WHERE ID > 1;

SELECT * FROM CUSTOMER WHERE ID <= 4;

SELECT * FROM CUSTOMER WHERE ID != 1;

SELECT * FROM CUSTOMER WHERE ADDRESS = '인천' OR ADDRESS = '서울';
SELECT * FROM CUSTOMER WHERE NOT ADDRESS = '서울';

SELECT * FROM ORDERS;
SELECT ORDER_ID + (SALESMAN_ID * ORDER_ID) FROM ORDERS;
SELECT ORDER_ID * SALESMAN_ID AS HAP FROM ORDERS;

SELECT '이름:'||NAME||'입니다.' AS INTRO FROM CUSTOMER;

SELECT * FROM CUSTOMER WHERE ID BETWEEN 2 AND 4;
SELECT * FROM CUSTOMER WHERE ID NOT BETWEEN 2 AND 4;
SELECT * FROM CUSTOMER WHERE ID IN(1,2,3);
SELECT * FROM CUSTOMER WHERE ID NOT IN(1,2,3);

SELECT * FROM CUSTOMER WHERE NAME LIKE '둘%'; -- '둘'로 시작하는 글자
SELECT * FROM CUSTOMER WHERE NAME LIKE '%길%'; -- 중간 글자가 '길'인 글자
SELECT * FROM CUSTOMER WHERE NAME LIKE '%치'; -- '치'로 끝나는 글자

SELECT * FROM CUSTOMER WHERE ADDRESS IS NULL;
SELECT * FROM CUSTOMER WHERE ADDRESS IS NOT NULL;

-- 데이터 조회 퀴즈
SELECT * FROM BOOK;
SELECT * FROM BOOK WHERE PRICE IN(11000, 25000);

SELECT * FROM BOOK WHERE PRICE > 30000;

SELECT * FROM BOOK WHERE PRICE BETWEEN 10000 AND 30000;

SELECT * FROM BOOK WHERE PUBLISHER IN('한빛미디어', '생능출판');

SELECT * FROM ORDERS;
SELECT * FROM ORDERS WHERE ORDER_DATE > '22/01/02';

SELECT * FROM ORDERS WHERE ORDER_DATE IN('22/01/01');

SELECT * FROM BOOK;
SELECT * FROM BOOK WHERE PRICE BETWEEN 10000 AND 30000;

SELECT * FROM CONTACTS;
SELECT * FROM CONTACTS WHERE FIRST_NAME IN('김', '최');

SELECT * FROM GIFT;
SELECT * FROM GIFT WHERE NAME IN('노트북', '벽걸이TV', '양쪽문냉장고');

SELECT * FROM GIFT WHERE TYPE IN('생활용품', '운동장비');

SELECT * FROM GIFT WHERE PRICE BETWEEN 300000 AND 600000;

SELECT * FROM CONTACTS;
SELECT * FROM CONTACTS WHERE PHONE LIKE '%2341';

SELECT * FROM CONTACTS WHERE PHONE LIKE '%3171%';

SELECT * FROM CONTACTS WHERE EMAIL LIKE '%@naver.com%' AND PHONE IS NULL;

SELECT * FROM GIFT;
SELECT * FROM GIFT WHERE NAME LIKE '%용품%';

SELECT * FROM GIFT WHERE NAME LIKE '%세트' AND PRICE <= 300000;

SELECT LTRIM('    JENNIE') FROM DUAL; -- 왼쪽 공백 제거
SELECT LTRIM('블랙핑크', '블랙') FROM DUAL; -- 왼쪽에서부터 '블랙' 글자 삭제

SELECT RTRIM('JENNIE    ') FROM DUAL; -- 오른쪽 공백 제거
SELECT RTRIM('블랙핑크', '핑크') FROM DUAL; -- 오른쪽에서부터 '핑크' 글자 삭제

SELECT TRIM('   JENNIE   ') FROM DUAL; -- 양쪽 공백 제거
SELECT TRIM(LEADING '블' FROM '블랙핑크') FROM DUAL; -- 왼쪽에서부터 '블' 삭제
SELECT TRIM(TRAILING '크' FROM '블랙핑크') FROM DUAL; -- 오른쪽에서부터 '크' 삭제
SELECT TRIM(BOTH '블' FROM '블랙핑크블') FROM DUAL; -- 양쪽 '블' 삭제

SELECT SUBSTR('블랙핑크제니', 3, 2) FROM DUAL;
SELECT SUBSTR('블랙핑크제니', 3, 4) FROM DUAL;

SELECT LENGTH('JENNIE') FROM DUAL;

SELECT REPLACE('블랙핑크제니', '제니', '지수') FROM DUAL;
SELECT REPLACE('블랙핑크제니', '블랙') FROM DUAL;

SELECT ABS(-1) FROM DUAL;
SELECT SIGN(-5) FROM DUAL; -- 부호

-- 지정된 소수 자리수까지 반올림 반환
SELECT ROUND(163.76, 1) FROM DUAL;
SELECT ROUND(163.76, -2) FROM DUAL;

-- 지정된 소수 자리수까지 버림 반환
SELECT TRUNC(54.29, 1) FROM DUAL;
SELECT TRUNC(54.29, -2) FROM DUAL;

SELECT CEIL(72.86) FROM DUAL; -- 소수점 이하의 수를 올림
SELECT FLOOR(22.3) FROM DUAL; -- 소수점 이하의 수를 버림

SELECT MOD(15, 7) FROM DUAL; -- 나머지


SELECT EXTRACT(YEAR FROM SYSDATE) AS YEAR,
       EXTRACT(MONTH FROM SYSDATE) AS MONTH,
       EXTRACT(DAY FROM SYSDATE) AS DAY
FROM DUAL;

SELECT ADD_MONTHS(TO_DATE('2021-12-31', 'YYYY-MM-DD'), -1) AS PRE FROM DUAL;

SELECT TO_NUMBER('1234') FROM DUAL; -- 문자 -> 숫자
SELECT TO_NUMBER('ABS') FROM DUAL; -- 에러

SELECT TO_CHAR(1234) FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD HH24MISS') FROM DUAL; -- 날짜 -> 문자 변경 포맷팅 가능

SELECT * FROM CUSTOMER;
SELECT NAME, NVL(ADDRESS, '주소없음') AS ADDRESS FROM CUSTOMER;

SELECT NAME, NULLIF(ADDRESS, '인천') AS ADDRESS FROM CUSTOMER;

SELECT ID, DECODE(ID, 1, 'BLUE', 2, 'RED', 3, 'YELLOW', 4, 'BLACK', 5, 'WHITE')
FROM CUSTOMER;

SELECT ID, CASE WHEN ID = 1 THEN 'BLUE'
                WHEN ID = 2 THEN 'RED'
                WHEN ID = 3 THEN 'YELLOW'
                WHEN ID = 4 THEN 'BLACK'
                ELSE 'WHITE'
           END AS TEST
FROM CUSTOMER;

-- 함수 퀴즈
-- QUIZ 1 정답 2번
SELECT MOD(-15, 0) FROM DUAL;
-- QUIZ 2 정답 1번
SELECT RTRIM(LTRIM(' SQ L D  ')) FROM DUAL;
-- QUIZ 3 정답 2번
SELECT ADD_MONTHS(TO_DATE('2022-01-31'), 1) FROM DUAL;
-- QUIZ 4
SELECT NAME, CASE WHEN NAME = '둘리' THEN 'BLUE'
                  WHEN NAME = '또치' THEN 'RED'
                  ELSE 'WHITE'
             END AS TEST
FROM CUSTOMER;



